<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace dmstr\modules\publication\models\crud\base;

use Yii;
use yii\behaviors\TimestampBehavior;

/**
 * This is the base-model class for table "{{%dmstr_publication_item}}".
 *
 * @property integer $id
 * @property integer $publication_category_id
 * @property string $content_widget_json
 * @property string $teaser_widget_json
 * @property string $status
 * @property string $release_date
 * @property string $end_date
 * @property integer $created_at
 * @property integer $updated_at
 *
 * @property \dmstr\modules\publication\models\crud\PublicationCategory $publicationCategory
 * @property string $aliasModel
 */
abstract class PublicationItem extends \yii\db\ActiveRecord
{



    /**
    * ENUM field values
    */
    const STATUS_DRAFT = 'draft';
    const STATUS_PUBLISHED = 'published';
    var $enum_labels = false;
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%dmstr_publication_item}}';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => TimestampBehavior::className(),
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['publication_category_id'], 'integer'],
            [['content_widget_json', 'teaser_widget_json', 'status'], 'string'],
            [['release_date', 'end_date'], 'safe'],
            [['publication_category_id'], 'exist', 'skipOnError' => true, 'targetClass' => \dmstr\modules\publication\models\crud\PublicationCategory::className(), 'targetAttribute' => ['publication_category_id' => 'id']],
            ['status', 'in', 'range' => [
                    self::STATUS_DRAFT,
                    self::STATUS_PUBLISHED,
                ]
            ]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('models', 'ID'),
            'publication_category_id' => Yii::t('models', 'Publication Category ID'),
            'content_widget_json' => Yii::t('models', 'Content Widget Json'),
            'teaser_widget_json' => Yii::t('models', 'Teaser Widget Json'),
            'status' => Yii::t('models', 'Status'),
            'release_date' => Yii::t('models', 'Release Date'),
            'end_date' => Yii::t('models', 'End Date'),
            'created_at' => Yii::t('models', 'Created At'),
            'updated_at' => Yii::t('models', 'Updated At'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPublicationCategory()
    {
        return $this->hasOne(\dmstr\modules\publication\models\crud\PublicationCategory::className(), ['id' => 'publication_category_id']);
    }


    
    /**
     * @inheritdoc
     * @return \dmstr\modules\publication\models\crud\query\PublicationItemQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \dmstr\modules\publication\models\crud\query\PublicationItemQuery(get_called_class());
    }


    /**
     * get column status enum value label
     * @param string $value
     * @return string
     */
    public static function getStatusValueLabel($value){
        $labels = self::optsStatus();
        if(isset($labels[$value])){
            return $labels[$value];
        }
        return $value;
    }

    /**
     * column status ENUM value labels
     * @return array
     */
    public static function optsStatus()
    {
        return [
            self::STATUS_DRAFT => Yii::t('models', self::STATUS_DRAFT),
            self::STATUS_PUBLISHED => Yii::t('models', self::STATUS_PUBLISHED),
        ];
    }

}
