<?php
/**
 * /app/src/../runtime/giiant/4b7e79a8340461fe629a6ac612644d03
 *
 * @package default
 */


use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use \dmstr\bootstrap\Tabs;
use yii\helpers\StringHelper;

/**
 *
 * @var yii\web\View $this
 * @var dmstr\modules\publication\models\crud\PublicationCategory $model
 * @var yii\widgets\ActiveForm $form
 */
?>

<div class="publication-category-form">

    <?php $form = ActiveForm::begin([
		'id' => 'PublicationCategory',
		'layout' => 'horizontal',
		'enableClientValidation' => true,
		'errorSummaryCssClass' => 'error-summary alert alert-danger',
		'fieldConfig' => [
			'template' => "{label}\n{beginWrapper}\n{input}\n{hint}\n{error}\n{endWrapper}",
			'horizontalCssClasses' => [
				'label' => 'col-sm-2',
				//'offset' => 'col-sm-offset-4',
				'wrapper' => 'col-sm-8',
				'error' => '',
				'hint' => '',
			],
		],
	]
);
?>

    <div class="">
        <?php $this->beginBlock('main'); ?>

        <p>


<!-- attribute content_widget_template_id -->
			<?php echo // generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::activeField
$form->field($model, 'content_widget_template_id')->widget(\kartik\select2\Select2::classname(), [
		'name' => 'class_name',
		'model' => $model,
		'attribute' => 'content_widget_template_id',
		'data' => \yii\helpers\ArrayHelper::map(dmstr\modules\publication\models\crud\HrzgWidgetTemplate::find()->all(), 'id', 'name'),
		'options' => [
			'placeholder' => Yii::t('cruds', 'Type to autocomplete'),
			'multiple' => false,
			'disabled' => (isset($relAttributes) && isset($relAttributes['content_widget_template_id'])),
		]
	]); ?>

<!-- attribute teaser_widget_template_id -->
			<?php echo // generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::activeField
$form->field($model, 'teaser_widget_template_id')->widget(\kartik\select2\Select2::classname(), [
		'name' => 'class_name',
		'model' => $model,
		'attribute' => 'teaser_widget_template_id',
		'data' => \yii\helpers\ArrayHelper::map(dmstr\modules\publication\models\crud\HrzgWidgetTemplate::find()->all(), 'id', 'name'),
		'options' => [
			'placeholder' => Yii::t('cruds', 'Type to autocomplete'),
			'multiple' => false,
			'disabled' => (isset($relAttributes) && isset($relAttributes['teaser_widget_template_id'])),
		]
	]); ?>

<!-- attribute name -->
			<?php echo $form->field($model, 'name')->textInput(['maxlength' => true]) ?>

<!-- attribute status -->
			<?php
$model->status = dmstr\modules\publication\models\crud\PublicationCategory::STATUS_PUBLISHED;
?>
			<?php echo                     $form->field($model, 'status')->radioList(
	dmstr\modules\publication\models\crud\PublicationCategory::optsstatus()
); ?>
        </p>
        <?php $this->endBlock(); ?>

        <?php echo
Tabs::widget(
	[
		'encodeLabels' => false,
		'items' => [
			[
				'label'   => Yii::t('models', 'PublicationCategory'),
				'content' => $this->blocks['main'],
				'active'  => true,
			],
		]
	]
);
?>
        <hr/>

        <?php echo $form->errorSummary($model); ?>

        <?php echo Html::submitButton(
	'<span class="glyphicon glyphicon-check"></span> ' .
	($model->isNewRecord ? Yii::t('cruds', 'Create') : Yii::t('cruds', 'Save')),
	[
		'id' => 'save-' . $model->formName(),
		'class' => 'btn btn-success'
	]
);
?>

        <?php ActiveForm::end(); ?>

    </div>

</div>
